### ISSUE TITLE
Websocket support?

### ISSUE THREAD

**Issue by s1037989** [flash548/mojo-gateway#8]
Does mojo-gateway support proxying web sockets, and if not do you have any intention of adding that support?

**Comment by flash548** [comment]
Hmmm havent really thought of that use case, therefore's hasnt been on my mind/roadmap.  What would that look like?  Right now its kind of a proxy-only from inbound traffic and respond to that request (vanilla HTTP transaction).

**Comment by s1037989** [comment]
So I think mojo-gateway aims to solve the same problem that I've been working on with [Mojolicious::Plugin::ProxyPass](https://github.com/stefanadams/Mojolicious-Plugin-ProxyPass/blob/main/lib/Mojolicious/Plugin/ProxyPass.pm#L61) and that is to be a reverse proxy just like nginx.  Users want to access a web app that is hidden on a network and can't reach directly, so they access the mojo proxy server which will then forward the request to the upstream server and the response back to the browser.  So this is fine, but what about when the hidden web app has web socket functionality?  The proxy server needs to be able to support web sockets.  When I posted this question, I didn't know how to proxy websockets, but now I'm [at least partially successful](https://github.com/stefanadams/Mojolicious-Plugin-ProxyPass/blob/main/lib/Mojolicious/Plugin/ProxyPass.pm#L135).

How does mojo-gateway's use case compare to this, and do you see that websocket support might be necessary depending on what you're proxying?

**Comment by flash548** [comment]
From my limited exposure to websocket usage, I think this would require some sort of state to be kept by mojo-gateway... vs it being a state-less proxy right now.  Logic/state would have to track the persistent client connections, which would tie up resources (potentially).  So at this time I dont plan on anything like this.  Interesting concept though.

**Comment by s1037989** [comment]
Just checking, this was just a Closed, not a Completed, correct?

How do you find performance to be? A few months ago I asked the mojo list about using mojolicious as an alternative to nginx but kraih thought that was a pretty terrible idea. I can understand it's not as performant but it's obviously good enough to be an app server so why not a proxy for another app? I'm using mojolicious to proxy atlassian confluence in production and there hasn't been a single complaint!

**Comment by flash548** [comment]
Correct. Not intending to implement.  Sorry I should have left a comment!!  

Yeah been using mojolicious as well for similar things as you're describing - works great!

**Comment by s1037989** [comment]
Understood, thanks for the clarification, and the confirmation about your experience! I find mojolicious (if perhaps slower) to be so much nicer to configure, control, monitor, extend, etc, than nginx!
